const tribunais = {
    "TJ-AC": "Tribunal de Justiça do Acre",
    "TJ-AL": "Tribunal de Justiça de Alagoas",
    "TJ-AP": "Tribunal de Justiça do Amapá",
    "TJ-AM": "Tribunal de Justiça do Amazonas",
    "TJ-BA": "Tribunal de Justiça da Bahia",
    "TJ-CE": "Tribunal de Justiça do Ceará",
    "TJ-DF": "Tribunal de Justiça do Distrito Federal e dos Territórios",
    "TJ-ES": "Tribunal de Justiça do Espírito Santo",
    "TJ-GO": "Tribunal de Justiça de Goiás",
    "TJ-MA": "Tribunal de Justiça do Maranhão",
    "TJ-MT": "Tribunal de Justiça do Mato Grosso",
    "TJ-MS": "Tribunal de Justiça do Mato Grosso do Sul",
    "TJ-MG": "Tribunal de Justiça de Minas Gerais",
    "TJ-PA": "Tribunal de Justiça do Pará",
    "TJ-PB": "Tribunal de Justiça da Paraíba",
    "TJ-PR": "Tribunal de Justiça do Paraná",
    "TJ-PE": "Tribunal de Justiça de Pernambuco",
    "TJ-PI": "Tribunal de Justiça do Piauí",
    "TJ-RJ": "Tribunal de Justiça do Rio de Janeiro",
    "TJ-RN": "Tribunal de Justiça do Rio Grande do Norte",
    "TJ-RS": "Tribunal de Justiça do Rio Grande do Sul",
    "TJ-RO": "Tribunal de Justiça de Rondônia",
    "TJ-RR": "Tribunal de Justiça de Roraima",
    "TJ-SC": "Tribunal de Justiça de Santa Catarina",
    "TJ-SP": "Tribunal de Justiça de São Paulo",
    "TJ-SE": "Tribunal de Justiça de Sergipe",
    "TJ-TO": "Tribunal de Justiça do Tocantins",
    "TRF1": "Tribunal Regional Federal da 1ª Região",
    "TRF2": "Tribunal Regional Federal da 2ª Região",
    "TRF3": "Tribunal Regional Federal da 3ª Região",
    "TRF4": "Tribunal Regional Federal da 4ª Região",
    "TRF5": "Tribunal Regional Federal da 5ª Região",
    "TRT-1": "Tribunal Regional do Trabalho da 1ª Região",
    "TRT-2": "Tribunal Regional do Trabalho da 2ª Região",
    "TRT-3": "Tribunal Regional do Trabalho da 3ª Região",
    "TRT-4": "Tribunal Regional do Trabalho da 4ª Região",
    "TRT-5": "Tribunal Regional do Trabalho da 5ª Região",
    "TRT-6": "Tribunal Regional do Trabalho da 6ª Região",
    "TRT-7": "Tribunal Regional do Trabalho da 7ª Região",
    "TRT-8": "Tribunal Regional do Trabalho da 8ª Região",
    "TRT-9": "Tribunal Regional do Trabalho da 9ª Região",
    "TRT-10": "Tribunal Regional do Trabalho da 10ª Região",
    "TRT-11": "Tribunal Regional do Trabalho da 11ª Região",
    "TRT-12": "Tribunal Regional do Trabalho da 12ª Região",
    "TRT-13": "Tribunal Regional do Trabalho da 13ª Região",
    "TRT-14": "Tribunal Regional do Trabalho da 14ª Região",
    "TRT-15": "Tribunal Regional do Trabalho da 15ª Região",
    "TRT-16": "Tribunal Regional do Trabalho da 16ª Região",
    "TRT-17": "Tribunal Regional do Trabalho da 17ª Região",
    "TRT-18": "Tribunal Regional do Trabalho da 18ª Região",
    "TRT-19": "Tribunal Regional do Trabalho da 19ª Região",
    "TRT-20": "Tribunal Regional do Trabalho da 20ª Região",
    "TRT-21": "Tribunal Regional do Trabalho da 21ª Região",
    "TRT-22": "Tribunal Regional do Trabalho da 22ª Região",
    "TRT-23": "Tribunal Regional do Trabalho da 23ª Região",
    "TRT-24": "Tribunal Regional do Trabalho da 24ª Região",
    "STJ": "Superior Tribunal de Justiça",
    "STF": "Supremo Tribunal Federal"
}
